services:
  app:
    ports:
      - "58000:8000"
    volumes:
      - ./Space-Pin-Pong:/app
      - /app/entrypoint  # entrypoint.sh의 권한 문제로 바인드 마운트 방지
    env_file:
      - ./env/.env.app.local
      - ./env/.env.db.local
      - ./env/.env.redis.local
    command: /app/entrypoint/docker-entrypoint.local.sh

  db:
    ports:
      - "55432:5432"
    env_file:
      - ./env/.env.db.local
    volumes:
      - postgres_data_local:/var/lib/postgresql/data/

  redis:
    ports:
      - "56379:6379"

volumes:
  postgres_data_local:
  django_logs_local:
