services:
  app:
    build:
      context: ./Space-Pin-Pong
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.7-bookworm
    restart: always

  redis:
    image: redis:7.4.0
    restart: always

