version: '3.8'

services:
  app:
    ports:
      - "58000:8000"
      - "50022:22"
    volumes:
      - ./Space-Pin-Pong:/app
      - /app/entrypoint
    env_file:
      - ./env/.env.app.local
      - ./env/.env.db.local

  db:
    ports:
      - "55432:5432"
    env_file:
      - ./env/.env.db.local

