version: '3.8'

services:
  app:
    build:
      context: ./Space-Pin-Pong
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15.7-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  django_logs:
