services:
  app:
    build:
      context: ./Space-Pin-Pong
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.7-bookworm
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.4.0
    restart: always


volumes:
  postgres_data:
  django_logs:
