# Generated by Django 5.0.7 on 2024-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friend_friend_unique_friend_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', '보류 중'), ('accept', '수락'), ('reject', '거절')], default='보류 중', max_length=20),
        ),
    ]
