name: "✨ 기능 요청"
description: 새로운 기능을 제안하기 위한 티켓을 생성합니다.
title: "✨ [FEATURE] - <제목>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "기능 설명"
      description: 제안하는 기능에 대한 자세한 설명을 입력해주세요
      placeholder: 기능의 구체적이고 명확한 설명...
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: "기능 필요성"
      description: 이 기능이 필요한 이유와 문제점을 설명해주세요
      placeholder: 이 기능이 필요한 이유 및 문제점 설명...
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: "예상 결과"
      description: 이 기능이 추가되었을 때 기대되는 결과를 설명해주세요
      placeholder: 기능 추가 후 기대되는 결과 설명...
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: "대안 솔루션"
      description: 고려한 다른 대안 솔루션이나 기능이 있다면 설명해주세요
      placeholder: 다른 대안이나 솔루션 설명...
    validations:
      required: false
