version: '3.8'

services:
  frontend:
    container_name: frontend
    image: front_end
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    image: back_end
    build: ./backend
    ports:
      - "3000:3000"
